export const DEFAULT_ACTIVITY_DIR = '/tmp/constellagent-activity'
export const CLAUDE_MARKER_SUFFIX = '.claude'
export const CODEX_MARKER_SEGMENT = '.codex.'
export const GEMINI_MARKER_SEGMENT = '.gemini.'
export const CURSOR_MARKER_SEGMENT = '.cursor.'
export const OPENCODE_MARKER_SEGMENT = '.opencode.'
